name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: sudo apt install curl libsqlite3-tcl sqlite3 tcl tcllib
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build
      run: make tinyfts
    - name: Run tests
      run: make test
    
